return {
	{
		"mason-org/mason.nvim",
		opts = {},
	},
	{
		"mason-org/mason-lspconfig.nvim",
		dependencies = { "mason-org/mason.nvim" },
		opts = {
			ensure_installed = {
				"angularls",
				"astro",
				"bashls",
				"clangd",
				"cobol_ls",
				"cssls",
				"docker_compose_language_service",
				"dockerls",
				"emmet_ls",
				"eslint",
				"graphql",
				"helm_ls",
				"html",
				"jdtls",
				"jsonls",
				"lua_ls",
				"marksman",
				"pyright",
				"ruff",
				"sqlls",
				"taplo",
				"ts_ls",
				"yamlls",
			},
		},
	},
}
